name: Unit on Chrome
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-16.04
    name: Unit on Chrome
    steps:
      - uses: actions/checkout@v2
      - uses: cypress-io/github-action@v2
        with:
          browser: chrome
  env:
    CYPRESS_RECORD_KEY: $RECORD_KEY